### ISSUE TITLE
Farbe des Linktextes im Ausdruck hat schlechten Kontrast

### ISSUE THREAD

**Issue by auge8472** [auge8472/SelfForum#5]
Der Linktext bereits besuchter Seiten wird im Ausdruck schwarz ausgegeben. Demgegenüber wird der Linktext unbesuchter Seiten hellblau beziehungsweise -grau angezeigt.

Schlechtes Kontrastverhältnis. _Minuspunkt!_

**Comment by MatthiasApsel** [comment]
```
.print .posting-content a {
    color: inherit;
}
```

**Comment by MatthiasApsel** [comment]
Konkret habe ich das so gemacht:

```
.print-preview .thread-message.print .posting-content a {
        color: inherit;
}
```

**Comment by auge8472** [comment]
Ja, das ist ja einfach. Leider vergisst sich das so schnell, wenn man es nicht benutzt Das wird übernommen, wie du es vorschlägst.
